// Auto-generated by Axion Visual Scripting
using System;
using AxionScriptCore;

public class Player : Entity {

	public override void OnCreate() {
		this.Audio.Play();
		this.RigidBody.AddForce(this.Transform.Position);
		this.EmitParticles(30);
		if ((0.100000f == 0.000000f)) {
			this.RigidBody.AddForce(new Vector3(0.400000f, 0.900000f, 1.300000f));
		} else {
			this.Audio.Play();
		}
	}

	public override void OnUpdate(float timestep) {
	}

	public override void OnCollisionEnter(Collision col) {
	}

}
