// Auto-generated by Axion Visual Scripting
using System;
using AxionScriptCore;

public class SunLight : Entity {

	public float Var_0 = 0.0f;

	public override void OnUpdate(float timestep) {
		this.Var_0 = ((this.Transform.Rotation).Y + 0.2f);
		this.Transform.Rotation = new Vector3((this.Transform.Rotation).X, this.Var_0, (this.Transform.Rotation).Z);
	}

}
