// Auto-generated by Axion Visual Scripting
using System;
using AxionScriptCore;

public class test : Entity {


	public override void OnCreate() {
	}

	public override void OnUpdate(float timestep) {
	}

	public override void OnCollisionEnter(Collision col) {
	}

}
