StartupProject: D:/Projects/TestProject/TestProject.axproj
MaxAssetsPerFrame: 2
ContentBrowser:
  ShowFileExtensions: true
  OnlyEngineAssets: true
  ThumbnailSize: 107
  TreeViewWidth: 340
  TreeViewTopHeight: 87
OpenTextEditors:
  - D:\Projects\TestProject\AssetRegistry.yaml
AssetLibraryPaths:
  - D:\Coding\AxionEngine\Axion\AxionStudioProject\AxionStudio\Resources\DefaultAssets