#pragma once

#define AX_MAX_SWAPCHAIN_BUFFERS 2

#define AX_D12_MAX_RTV_DESCRIPTORS 16
#define AX_D12_MAX_SRV_DESCRIPTORS 256
#define AX_D12_MAX_DSV_DESCRIPTORS 16
#define AX_D12_ENABLE_DEBUG_SEVERITY_WARNING 0
#define AX_D12_ENABLE_DEBUG_GPU_BASED_VALIDATION 0

#define AX_WIN_USING_CUSTOM_TITLE_BAR 1
