#pragma once

// ----- ENGINE -----
#define AX_ENGINE_VERSION "0.1.0"

#define AX_MAX_SWAPCHAIN_BUFFERS 2


// ----- DirectX12 -----
#define AX_D12_MAX_RTV_DESCRIPTORS 16
#define AX_D12_MAX_SRV_DESCRIPTORS 1024
#define AX_D12_MAX_DSV_DESCRIPTORS 16
#define AX_D12_ENABLE_DEBUG_SEVERITY_WARNING 0
#define AX_D12_ENABLE_DEBUG_GPU_BASED_VALIDATION 0


// ----- Win32 -----
#define AX_WIN_USING_CUSTOM_TITLE_BAR 0
