#include "VisualScriptCompiler.h"

namespace Axion {

	std::string VisualScriptCompiler::compileGraph(const VisualGraph& graph) {
		std::stringstream cs;

		cs << "// Auto-generated by Axion Visual Scripting\n";
		cs << "using System;\n";
		cs << "using AxionScriptCore;\n\n";
		cs << "public class " << graph.className << " : Entity {\n\n";

		// -- Create Variables --
		for (const auto& var : graph.variables) {
			if (var.type == PinType::Float) {
				cs << "\tpublic float " << var.name << " = " << formatFloat(var.floatValue) << ";\n";
			}
			else if (var.type == PinType::Int) {
				cs << "\tpublic int " << var.name << " = " << var.intValue << ";\n";
			}
			else if (var.type == PinType::Bool) {
				cs << "\tpublic bool " << var.name << " = " << (var.boolValue ? "true" : "false") << ";\n";
			}
			else if (var.type == PinType::Vector3) {
				cs << "\tpublic Vector3 " << var.name << " = new Vector3(" << formatFloat(var.vec3Value.x) << ", " << formatFloat(var.vec3Value.y) << ", " << formatFloat(var.vec3Value.z) << ");\n";
			}
		}
		cs << "\n";

		// -- Create Code --
		for (const auto& node : graph.nodes) {

			if (node.outputs.empty()) continue;

			if (node.type == NodeType::Event_OnCreate) {
				cs << "\tpublic override void OnCreate() {\n";
				compileFlowExecution(graph, node.outputs[0].id, cs, 2);
				cs << "\t}\n\n";
			}
			else if (node.type == NodeType::Event_OnUpdate) {
				cs << "\tpublic override void OnUpdate(float timestep) {\n";
				compileFlowExecution(graph, node.outputs[0].id, cs, 2);
				cs << "\t}\n\n";
			}
			else if (node.type == NodeType::Event_OnCollisionEnter) {
				cs << "\tpublic override void OnCollisionEnter(Collision col) {\n";
				compileFlowExecution(graph, node.outputs[0].id, cs, 2);
				cs << "\t}\n\n";
			}
		}

		cs << "}\n";
		return cs.str();
	}

	std::string VisualScriptCompiler::getInlineValueString(const Pin& pin) {
		switch (pin.type) {
			case PinType::Float: { return formatFloat(pin.floatValue); }
			case PinType::Int: { return std::to_string(pin.intValue); }
			case PinType::Bool: { return pin.boolValue ? "true" : "false"; }
			case PinType::String: { return "\"" + pin.stringValue + "\""; }
			case PinType::Vector3: { return "new Vector3(" + formatFloat(pin.vec3Value.x) + ", " + formatFloat(pin.vec3Value.y) + ", " + formatFloat(pin.vec3Value.z) + ")"; }
			default: return "";
		}
	}

	std::string VisualScriptCompiler::formatFloat(float value) {
		std::string str = std::to_string(value);

		str.erase(str.find_last_not_of('0') + 1, std::string::npos);

		if (str.back() == '.') str += "0";

		return str + "f";
	}

	std::string VisualScriptCompiler::resolvePinValue(const VisualGraph& graph, const Pin& inputPin) {
		for (const auto& link : graph.links) {
			if (link.endPinID == inputPin.id) {
				for (const auto& sourceNode : graph.nodes) {
					for (const auto& outputPin : sourceNode.outputs) {
						if (outputPin.id == link.startPinID) {

							auto safeResolve = [&](size_t idx) -> std::string {
								if (idx >= sourceNode.inputs.size()) return "null /* ERROR_MISSING_PIN */";
								return resolvePinValue(graph, sourceNode.inputs[idx]);
							};

							auto safeRawString = [&](size_t idx) -> std::string {
								if (idx >= sourceNode.inputs.size()) return "";
								return sourceNode.inputs[idx].stringValue;
							};

							// -- EVENTS --
							if (sourceNode.type == NodeType::Event_OnUpdate && outputPin.name == "Delta Time") return "timestep";
							if (sourceNode.type == NodeType::Event_OnCollisionEnter && outputPin.name == "Other Entity") return "col.OtherEntity";

							// -- ENTITY --
							if (sourceNode.type == NodeType::Entity_Instantiate) return "Entity.Instantiate(" + safeResolve(1) + ")";
							if (sourceNode.type == NodeType::Entity_InstantiatePrefab) return "Entity.InstantiatePrefab(" + safeResolve(1) + ")";
							if (sourceNode.type == NodeType::Entity_FindByName) return "Entity.FindEntityByName(" + safeResolve(0) + ")";

							// -- INPUT --
							if (sourceNode.type == NodeType::Input_IsKeyPressed) return "Input.IsKeyPressed(KeyCode." + safeRawString(0) + ")";
							if (sourceNode.type == NodeType::Input_IsMouseButtonPressed) return "Input.IsMouseButtonPressed(MouseButton." + safeRawString(0) + ")";

							// -- MATH --
							if (sourceNode.type == NodeType::Math_Add) return "(" + safeResolve(0) + " + " + safeResolve(1) + ")";
							if (sourceNode.type == NodeType::Math_Subtract) return "(" + safeResolve(0) + " - " + safeResolve(1) + ")";
							if (sourceNode.type == NodeType::Math_Multiply) return "(" + safeResolve(0) + " * " + safeResolve(1) + ")";
							if (sourceNode.type == NodeType::Math_Divide) return "(" + safeResolve(0) + " / " + safeResolve(1) + ")";
							if (sourceNode.type == NodeType::Math_Equal) return "(" + safeResolve(0) + " == " + safeResolve(1) + ")";
							if (sourceNode.type == NodeType::Math_Greater) return "(" + safeResolve(0) + " > " + safeResolve(1) + ")";
							if (sourceNode.type == NodeType::Math_Less) return "(" + safeResolve(0) + " < " + safeResolve(1) + ")";

							// -- LOGIC (PURE) --
							if (sourceNode.type == NodeType::Logic_And) return "(" + safeResolve(0) + " && " + safeResolve(1) + ")";
							if (sourceNode.type == NodeType::Logic_Or) return "(" + safeResolve(0) + " || " + safeResolve(1) + ")";

							if (sourceNode.type == NodeType::Math_MakeVector3) {
								return "new Vector3(" + safeResolve(0) + ", " + safeResolve(1) + ", " + safeResolve(2) + ")";
							}

							if (sourceNode.type == NodeType::Math_BreakVector3) {
								std::string vec = safeResolve(0);
								if (outputPin.name == "X") return "(" + vec + ").X";
								if (outputPin.name == "Y") return "(" + vec + ").Y";
								if (outputPin.name == "Z") return "(" + vec + ").Z";
							}

							// -- Resolve Target for Components --
							std::string target = safeResolve(0);
							if (target.empty() || target == "\"\"" || target == "null /* ERROR_MISSING_PIN */") target = "this";

							// -- TRANSFORM GETTERS --
							if (sourceNode.type == NodeType::Transform_GetPosition) return target + ".Transform.Position";
							if (sourceNode.type == NodeType::Transform_GetRotation) return target + ".Transform.Rotation";
							if (sourceNode.type == NodeType::Transform_GetScale) return target + ".Transform.Scale";
							if (sourceNode.type == NodeType::Transform_GetForward) return target + ".Transform.Forward";
							if (sourceNode.type == NodeType::Transform_GetRight) return target + ".Transform.Right";
							if (sourceNode.type == NodeType::Transform_GetUp) return target + ".Transform.Up";

							// -- RIGIDBODY GETTERS --
							if (sourceNode.type == NodeType::RigidBody_GetLinearVelocity) return target + ".RigidBody.LinearVelocity";
							if (sourceNode.type == NodeType::RigidBody_GetAngularVelocity) return target + ".RigidBody.AngularVelocity";
							if (sourceNode.type == NodeType::RigidBody_GetMass) return target + ".RigidBody.Mass";

							// -- AUDIO / ANIMATOR GETTERS --
							if (sourceNode.type == NodeType::Audio_GetVolume) return target + ".Audio.Volume";
							if (sourceNode.type == NodeType::Animator_IsPlaying) return target + ".Animator.IsPlaying";

							// -- VARIABLES (GET) --
							if (sourceNode.type == NodeType::Variable_GetFloat || sourceNode.type == NodeType::Variable_GetInt ||
								sourceNode.type == NodeType::Variable_GetVector3 || sourceNode.type == NodeType::Variable_GetBool) {
								std::string varName = safeResolve(0);
								if (varName.size() >= 2 && varName.front() == '"' && varName.back() == '"') {
									varName = varName.substr(1, varName.size() - 2);
								}
								return "this." + varName;
							}
						}
					}
				}
			}
		}

		return getInlineValueString(inputPin);
	}

	void VisualScriptCompiler::compileFlowExecution(const VisualGraph& graph, int currentFlowOutputPinID, std::stringstream& cs, int indentLevel) {
		std::string tabs(indentLevel, '\t');

		// -- Find the next node connected to the current execution pin --
		for (const auto& link : graph.links) {
			if (link.startPinID != currentFlowOutputPinID) continue;

			const Node* nextNode = nullptr;
			int nextFlowOutputID = -1;

			for (const auto& node : graph.nodes) {
				for (const auto& inputPin : node.inputs) {
					if (inputPin.id == link.endPinID && inputPin.type == PinType::Flow) {
						nextNode = &node;
						if (!node.outputs.empty() && node.outputs[0].type == PinType::Flow) {
							nextFlowOutputID = node.outputs[0].id;
						}
						break;
					}
				}
				if (nextNode) break;
			}

			if (!nextNode) continue;

			auto safeResolve = [&](size_t idx) -> std::string {
				if (idx >= nextNode->inputs.size()) return "null /* ERROR_MISSING_PIN */";
				return resolvePinValue(graph, nextNode->inputs[idx]);
			};

			// -- Resolve Target --
			std::string target = "this";
			if (nextNode->inputs.size() > 1 && nextNode->inputs[1].type == PinType::Entity) {
				target = safeResolve(1);
				if (target.empty() || target == "\"\"" || target == "null /* ERROR_MISSING_PIN */") target = "this";
			}

			// -- Generate Code --
			switch (nextNode->type) {
			// -- CONTROL FLOW --
				case NodeType::Logic_Branch: {
					std::string condition = safeResolve(1);
					// -- Generate If Block --
					cs << tabs << "if (" << condition << ") {\n";

					if (!nextNode->outputs.empty()) {
						compileFlowExecution(graph, nextNode->outputs[0].id, cs, indentLevel + 1);
					}

					// -- Generate False Block --
					bool hasFalseConnection = false;
					if (nextNode->outputs.size() > 1) {
						for (const auto& link : graph.links) {
							if (link.startPinID == nextNode->outputs[1].id) {
								hasFalseConnection = true;
								break;
							}
						}
					}

					if (hasFalseConnection && nextNode->outputs.size() > 1) {
						cs << tabs << "} else {\n";
						compileFlowExecution(graph, nextNode->outputs[1].id, cs, indentLevel + 1);
						cs << tabs << "}\n";
					}
					else {
						cs << tabs << "}\n";
					}

					continue;
				}
				case NodeType::Logic_Sequence: {
					for (const auto& pin : nextNode->outputs) {
						if (pin.type == PinType::Flow) {
							compileFlowExecution(graph, pin.id, cs, indentLevel);
						}
					}
					continue;
				}

				case NodeType::Entity_Destroy: {
					cs << tabs << target << ".Destroy();\n";
					break;
				}
				case NodeType::Entity_EmitParticles: {
					std::string count = safeResolve(2);
					cs << tabs << target << ".EmitParticles(" << count << ");\n";
					break;
				}

				// -- TRANSFORM --
				case NodeType::Transform_SetPosition: {
					std::string val = safeResolve(2);
					cs << tabs << target << ".Transform.Position = " << val << ";\n";
					break;
				}
				case NodeType::Transform_SetRotation: {
					std::string val = safeResolve(2);
					cs << tabs << target << ".Transform.Rotation = " << val << ";\n";
					break;
				}
				case NodeType::Transform_SetScale: {
					std::string val = safeResolve(2);
					cs << tabs << target << ".Transform.Scale = " << val << ";\n";
					break;
				}

				// -- RIGIDBODY --
				case NodeType::RigidBody_AddForce: {
					std::string force = safeResolve(2);
					cs << tabs << target << ".RigidBody.AddForce(" << force << ");\n";
					break;
				}
				case NodeType::RigidBody_AddTorque: {
					std::string torque = safeResolve(2);
					cs << tabs << target << ".RigidBody.AddTorque(" << torque << ");\n";
					break;
				}
				case NodeType::RigidBody_AddImpulse: {
					std::string force = safeResolve(2);
					cs << tabs << target << ".RigidBody.AddForce(" << force << ", ForceMode.Impulse);\n";
					break;
				}
				case NodeType::RigidBody_AddRadialImpulse: {
					std::string origin = safeResolve(2);
					std::string radius = safeResolve(3);
					std::string strength = safeResolve(4);
					cs << tabs << target << ".RigidBody.AddRadialImpulse(" << origin << ", " << radius << ", " << strength << ");\n";
					break;
				}
				case NodeType::RigidBody_SetLinearVelocity: {
					std::string vel = safeResolve(2);
					cs << tabs << target << ".RigidBody.LinearVelocity = " << vel << ";\n";
					break;
				}
				case NodeType::RigidBody_SetAngularVelocity: {
					std::string vel = safeResolve(2);
					cs << tabs << target << ".RigidBody.AngularVelocity = " << vel << ";\n";
					break;
				}
				case NodeType::RigidBody_SetMass: {
					std::string mass = safeResolve(2);
					cs << tabs << target << ".RigidBody.Mass = " << mass << ";\n";
					break;
				}

				// -- AUDIO --
				case NodeType::Audio_Play: cs << tabs << target << ".Audio.Play();\n"; break;
				case NodeType::Audio_Stop: cs << tabs << target << ".Audio.Stop();\n"; break;
				case NodeType::Audio_SetVolume: {
					std::string vol = safeResolve(2);
					cs << tabs << target << ".Audio.Volume = " << vol << ";\n";
					break;
				}

				// -- ANIMATOR --
				case NodeType::Animator_Play: cs << tabs << target << ".Animator.Play();\n"; break;
				case NodeType::Animator_Stop: cs << tabs << target << ".Animator.Stop();\n"; break;

				// -- VARIABLES SETTERS --
				case NodeType::Variable_SetFloat:
				case NodeType::Variable_SetInt:
				case NodeType::Variable_SetVector3:
				case NodeType::Variable_SetBool: {
					std::string varName = safeResolve(1);
					if (varName.size() >= 2 && varName.front() == '"' && varName.back() == '"') {
						varName = varName.substr(1, varName.size() - 2);
					}
					std::string val = safeResolve(2);
					cs << tabs << "this." + varName << " = " << val << ";\n";
					break;
				}

				default: break;
			}

			// -- Continue Down the White Wire --
			if (nextFlowOutputID != -1) {
				compileFlowExecution(graph, nextFlowOutputID, cs, indentLevel);
			}

		}
	}

}
