#include "VisualScriptCompiler.h"

namespace Axion {

	std::string VisualScriptCompiler::compileGraph(const VisualGraph& graph) {
		std::stringstream cs;

		cs << "// Auto-generated by Axion Visual Scripting\n";
		cs << "using System;\n";
		cs << "using AxionScriptCore;\n\n";
		cs << "public class " << graph.className << " : Entity {\n\n";

		for (const auto& node : graph.nodes) {

			if (node.type == NodeType::Event_OnCreate) {
				cs << "\tpublic override void OnCreate() {\n";
				compileFlowExecution(graph, node.outputs[0].id, cs, 2);
				cs << "\t}\n\n";
			}
			else if (node.type == NodeType::Event_OnUpdate) {
				cs << "\tpublic override void OnUpdate(float timestep) {\n";
				compileFlowExecution(graph, node.outputs[0].id, cs, 2);
				cs << "\t}\n\n";
			}
			else if (node.type == NodeType::Event_OnCollisionEnter) {
				cs << "\tpublic override void OnCollisionEnter(Collision col) {\n";
				compileFlowExecution(graph, node.outputs[0].id, cs, 2);
				cs << "\t}\n\n";
			}
		}

		cs << "}\n";
		return cs.str();
	}

	std::string VisualScriptCompiler::getInlineValueString(const Pin& pin) {
		switch (pin.type) {
			case PinType::Float: { return std::to_string(pin.floatValue) + "f"; }
			case PinType::Int: { return std::to_string(pin.intValue); }
			case PinType::Bool: { return pin.boolValue ? "true" : "false"; }
			case PinType::String: { return "\"" + pin.stringValue + "\""; }
			case PinType::Vector3: { return "new Vector3(" + std::to_string(pin.vec3Value.x) + "f, " + std::to_string(pin.vec3Value.y) + "f, " + std::to_string(pin.vec3Value.z) + "f)"; }
			default: return "";
		}
	}

	std::string VisualScriptCompiler::resolvePinValue(const VisualGraph& graph, const Pin& inputPin) {
		for (const auto& link : graph.links) {
			if (link.endPinID == inputPin.id) {
				for (const auto& sourceNode : graph.nodes) {
					for (const auto& outputPin : sourceNode.outputs) {
						if (outputPin.id == link.startPinID) {

							// -- EVENTS --
							if (sourceNode.type == NodeType::Event_OnUpdate && outputPin.name == "Delta Time") return "timestep";
							if (sourceNode.type == NodeType::Event_OnCollisionEnter && outputPin.name == "Other Entity") return "col.OtherEntity";

							// -- ENTITY --
							if (sourceNode.type == NodeType::Entity_Instantiate) return "Entity.Instantiate(" + resolvePinValue(graph, sourceNode.inputs[1]) + ")";
							if (sourceNode.type == NodeType::Entity_InstantiatePrefab) return "Entity.InstantiatePrefab(" + resolvePinValue(graph, sourceNode.inputs[1]) + ")";
							if (sourceNode.type == NodeType::Entity_FindByName) return "Entity.FindEntityByName(" + resolvePinValue(graph, sourceNode.inputs[0]) + ")";

							// -- INPUT --
							if (sourceNode.type == NodeType::Input_IsKeyPressed) return "Input.IsKeyPressed(KeyCode." + sourceNode.inputs[0].stringValue + ")";
							if (sourceNode.type == NodeType::Input_IsMouseButtonPressed) return "Input.IsMouseButtonPressed(MouseButton." + sourceNode.inputs[0].stringValue + ")";

							// -- MATH --
							if (sourceNode.type == NodeType::Math_Add) return "(" + resolvePinValue(graph, sourceNode.inputs[0]) + " + " + resolvePinValue(graph, sourceNode.inputs[1]) + ")";
							if (sourceNode.type == NodeType::Math_Subtract) return "(" + resolvePinValue(graph, sourceNode.inputs[0]) + " - " + resolvePinValue(graph, sourceNode.inputs[1]) + ")";
							if (sourceNode.type == NodeType::Math_Multiply) return "(" + resolvePinValue(graph, sourceNode.inputs[0]) + " * " + resolvePinValue(graph, sourceNode.inputs[1]) + ")";
							if (sourceNode.type == NodeType::Math_Divide) return "(" + resolvePinValue(graph, sourceNode.inputs[0]) + " / " + resolvePinValue(graph, sourceNode.inputs[1]) + ")";
							if (sourceNode.type == NodeType::Math_Equal) return "(" + resolvePinValue(graph, sourceNode.inputs[0]) + " == " + resolvePinValue(graph, sourceNode.inputs[1]) + ")";
							if (sourceNode.type == NodeType::Math_Greater) return "(" + resolvePinValue(graph, sourceNode.inputs[0]) + " > " + resolvePinValue(graph, sourceNode.inputs[1]) + ")";
							if (sourceNode.type == NodeType::Math_Less) return "(" + resolvePinValue(graph, sourceNode.inputs[0]) + " < " + resolvePinValue(graph, sourceNode.inputs[1]) + ")";

							// -- Resolve Target for Components --
							std::string target = resolvePinValue(graph, sourceNode.inputs[0]);
							if (target.empty() || target == "\"\"") target = "this";

							// -- TRANSFORM GETTERS --
							if (sourceNode.type == NodeType::Transform_GetPosition) return target + ".Transform.Position";
							if (sourceNode.type == NodeType::Transform_GetRotation) return target + ".Transform.Rotation";
							if (sourceNode.type == NodeType::Transform_GetScale) return target + ".Transform.Scale";
							if (sourceNode.type == NodeType::Transform_GetForward) return target + ".Transform.Forward";
							if (sourceNode.type == NodeType::Transform_GetRight) return target + ".Transform.Right";
							if (sourceNode.type == NodeType::Transform_GetUp) return target + ".Transform.Up";

							// -- RIGIDBODY GETTERS --
							if (sourceNode.type == NodeType::RigidBody_GetLinearVelocity) return target + ".RigidBody.LinearVelocity";
							if (sourceNode.type == NodeType::RigidBody_GetMass) return target + ".RigidBody.Mass";

							// -- AUDIO / ANIMATOR GETTERS --
							if (sourceNode.type == NodeType::Audio_GetVolume) return target + ".Audio.Volume";
							if (sourceNode.type == NodeType::Animator_IsPlaying) return target + ".Animator.IsPlaying";
						}
					}
				}
			}
		}

		return getInlineValueString(inputPin);
	}

	void VisualScriptCompiler::compileFlowExecution(const VisualGraph& graph, int currentFlowOutputPinID, std::stringstream& cs, int indentLevel) {
		std::string tabs(indentLevel, '\t');

		const Node* nextNode = nullptr;
		int nextFlowOutputID = -1;

		// -- Find the next node connected to the current execution pin --
		for (const auto& link : graph.links) {
			if (link.startPinID == currentFlowOutputPinID) {
				for (const auto& node : graph.nodes) {
					for (const auto& inputPin : node.inputs) {
						if (inputPin.id == link.endPinID && inputPin.type == PinType::Flow) {
							nextNode = &node;
							if (!node.outputs.empty() && node.outputs[0].type == PinType::Flow) {
								nextFlowOutputID = node.outputs[0].id;
							}
							break;
						}
					}
				}
			}
		}

		if (!nextNode) return;

		// -- Resolve Target --
		std::string target = "this";
		if (nextNode->inputs.size() > 1 && nextNode->inputs[1].type == PinType::Entity) {
			target = resolvePinValue(graph, nextNode->inputs[1]);
			if (target.empty() || target == "\"\"") target = "this";
		}

		switch (nextNode->type) {
			// -- CONTROL FLOW --
			case NodeType::Logic_Branch: {
				std::string condition = resolvePinValue(graph, nextNode->inputs[1]);
				cs << tabs << "if (" << condition << ") {\n";
				compileFlowExecution(graph, nextNode->outputs[0].id, cs, indentLevel + 1);
				cs << tabs << "} else {\n";
				compileFlowExecution(graph, nextNode->outputs[1].id, cs, indentLevel + 1);
				cs << tabs << "}\n";
				return;
			}

			// -- ENTITY --
			case NodeType::Entity_Destroy: {
				cs << tabs << target << ".Destroy();\n";
				break;
			}
			case NodeType::Entity_EmitParticles: {
				std::string count = resolvePinValue(graph, nextNode->inputs[2]);
				cs << tabs << target << ".EmitParticles(" << count << ");\n";
				break;
			}

			// -- TRANSFORM --
			case NodeType::Transform_SetPosition: {
				std::string val = resolvePinValue(graph, nextNode->inputs[2]);
				cs << tabs << target << ".Transform.Position = " << val << ";\n";
				break;
			}
			case NodeType::Transform_SetRotation: {
				std::string val = resolvePinValue(graph, nextNode->inputs[2]);
				cs << tabs << target << ".Transform.Rotation = " << val << ";\n";
				break;
			}
			case NodeType::Transform_SetScale: {
				std::string val = resolvePinValue(graph, nextNode->inputs[2]);
				cs << tabs << target << ".Transform.Scale = " << val << ";\n";
				break;
			}

			// -- RIGIDBODY --
			case NodeType::RigidBody_AddForce: {
				std::string force = resolvePinValue(graph, nextNode->inputs[2]);
				cs << tabs << target << ".RigidBody.AddForce(" << force << ");\n";
				break;
			}
			case NodeType::RigidBody_AddTorque: {
				std::string torque = resolvePinValue(graph, nextNode->inputs[2]);
				cs << tabs << target << ".RigidBody.AddTorque(" << torque << ");\n";
				break;
			}
			case NodeType::RigidBody_AddRadialImpulse: {
				std::string origin = resolvePinValue(graph, nextNode->inputs[2]);
				std::string radius = resolvePinValue(graph, nextNode->inputs[3]);
				std::string strength = resolvePinValue(graph, nextNode->inputs[4]);
				cs << tabs << target << ".RigidBody.AddRadialImpulse(" << origin << ", " << radius << ", " << strength << ");\n";
				break;
			}
			case NodeType::RigidBody_SetLinearVelocity: {
				std::string vel = resolvePinValue(graph, nextNode->inputs[2]);
				cs << tabs << target << ".RigidBody.LinearVelocity = " << vel << ";\n";
				break;
			}
			case NodeType::RigidBody_SetMass: {
				std::string mass = resolvePinValue(graph, nextNode->inputs[2]);
				cs << tabs << target << ".RigidBody.Mass = " << mass << ";\n";
				break;
			}

			// -- AUDIO --
			case NodeType::Audio_Play: cs << tabs << target << ".Audio.Play();\n"; break;
			case NodeType::Audio_Stop: cs << tabs << target << ".Audio.Stop();\n"; break;
			case NodeType::Audio_SetVolume: {
				std::string vol = resolvePinValue(graph, nextNode->inputs[2]);
				cs << tabs << target << ".Audio.Volume = " << vol << ";\n";
				break;
			}

			// -- ANIMATOR --
			case NodeType::Animator_Play: cs << tabs << target << ".Animator.Play();\n"; break;
			case NodeType::Animator_Stop: cs << tabs << target << ".Animator.Stop();\n"; break;

			default: break;
		}

		// Continue down the white wire
		if (nextFlowOutputID != -1) {
			compileFlowExecution(graph, nextFlowOutputID, cs, indentLevel);
		}
	}

}
